//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientSystem.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public System.Guid ID { get; set; }
        public string RegistrationNumber { get; set; }
        public string PatientName { get; set; }
        public string FatherName { get; set; }
        public int Age { get; set; }
        public string Address { get; set; }
        public string HealthIssue { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
