//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientSystem.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTiming
    {
        public System.Guid ID { get; set; }
        public System.Guid PatientID { get; set; }
        public System.Guid DoctorID { get; set; }
        public string Timing { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public System.DateTime AppointmentDate { get; set; }
    }
}
